### ISSUE TITLE
Deep architectural issues with adding new copies of existing objects to wad2

### ISSUE THREAD

**Issue by Lwmte** [MontyTRC89/Tomb-Editor#413]
There is a deep architectural flaw which prevents adding copies of already existing objects to same wad2. New object IDs are linked to already existing same objects in wad2. It happens because somewhere deep in wad2 object creation code, new object is somehow linked to old one.

You can reproduce this issue by doing this. Open WT, copy object from source to destination, and then copy it again but into different slot. You will get an exception: "Object already exists in dictionary". What happens under the hood is, as new object ID is linked to existing object ID, `Equals` method fails on new copy of the same object and throws this exception while `WadTreeControl` is trying to build item tree.

After further investigation, I have found where the issue is surfacing. It's in Wad2.cs file, line 182 onwards:

```
// Change id if necessary
if (newId != wadObject.Id)
{
	var property = wadObject.GetType().GetProperty("Id");
	property.SetValue(wadObject, newId);
}

// Add object
if (newId is WadMoveableId)
	Moveables.Add((WadMoveableId)newId, (WadMoveable)wadObject);
else if (newId is WadStaticId)
	Statics.Add((WadStaticId)newId, (WadStatic)wadObject);
else if (newId is WadSpriteSequenceId)
	SpriteSequences.Add((WadSpriteSequenceId)newId, (WadSpriteSequence)wadObject);
else
	throw new ArgumentException("Argument not of a valid type.");
```

When `property.SetValue(wadObject, newId);` happens, it doesn't modify ID for incoming object, **but also for already existing same object in wad2**! I tried to fix issue by cloning object on copying, but it seems there is another issue with `Clone` method for moveables (not for statics), because of which resulting moveable becomes invisible in preview window (and I guess it's just a visual representation of a more deep issue).

**Comment by Castigavi** [comment]
While checking the issue I have noticed that you can actually duplicate objects without issue, but only if you first close source wad, then reopen it.

Repro steps:
1. Open WADTool. Open or create a new destination wad and open a source wad with a movable object.
2. Add object from destination wad to source wad.
3. Try adding the same object again and observe, how "no objects were copied because they were already in different slots".
4. Open a different source wad, then open back previous source wad,
5. Try to copy same movable object to destination wad again. Notice that now you can successfully copy that object.

Because of that I propose to either modify current "Add object / Add object to different slots" function or add a new function that would **reload source wad** when user tries to add new copy of an existing object.

**Comment by Lwmte** [comment]
Fixed
