### ISSUE TITLE
Allow more than 5 subdivisions on a wall

### ISSUE THREAD

**Issue by ActuallyaDeviloper** [MontyTRC89/Tomb-Editor#48]
Currently there is a limit for 5 sub divisions on walls and only 2 on the floor and ceiling.
This is a very severe limit in my experience.
We should allow more than that. Possibly a practically infinite amount.

The A, Q, W, S, D, E, F, R kesy will not be good enough anymore since they only allow editing up to 4 lines.
A possible way around that would be to allow selecting the subvisions directly. Then for example rolling the mousewheel changes the height. If the subdivision is not valid anymore and is outside the visible range, we probably should automatically remove it, since its almost impossible to select it again. Without visibility, no selection and as a result also no removal. If we don't delete them automatically, probably a lot of invalid seams will accumulate over time that are not visible normally but are annoying when editing.

This change seems complicated.

**Comment by Joey79100** [comment]
I thought a little about how this could be implemented, and just noticed there was already an issue open for this.

Here's a visual representation of my idea, which is a bit different than the one above:
![image](https://user-images.githubusercontent.com/12445716/170720909-ff4b3a49-f838-439a-b0fa-49a887405c56.png)

Basically, when pressing ER/DF or any of the new shortcuts, highlight the currently selected subdivision for visual feedback.
New shortcuts allow the user to spawn/destroy additional subdivisions.
ER/DF will move the currently selected subdivision.

Exhaustive list of the new shortcuts:

## Floor:
**Alt+E** = Spawn new (or select if exists) subdivision **above** currently selected
**Alt+D** = Spawn new (or select if exists) subdivision **below** currently selected

**Alt+Shift+E** = Remove subdivision **above** currently selected
**Alt+Shift+D** = Remove subdivision **below** currently selected

## Ceiling:
**Alt+R** = Spawn new (or select if exists) subdivision **above** currently selected
**Alt+F** = Spawn new (or select if exists) subdivision **below** currently selected

**Alt+Shift+R** = Remove subdivision **above** currently selected
**Alt+Shift+F** = Remove subdivision **below** currently selected

**Comment by Nickelony** [comment]
We are currently allowing up to **9** subdivisions, one for each number key (`1` - `9`).
Subdivisions are dynamically created while using the **Drag** tool. To create a new subdivision, you must HOLD any number key and drag up / down with `Left Mouse Button`.
If a subdivision is in the void (out of bounds - not visible from any angle) it won't be saved into the prj2 file since it's considered invalid. Reloading the file will make the invalid subdivisions disappear to save memory.

Current ToDo:
- [ ] Optimize _faceTextures with a Dictionary instead of a fixed array of size [99];
- [ ] Fix Undo / Redo not functioning correctly;
- [ ] Refactor code and comment the heck out of it for future programmers;

**Comment by Nickelony** [comment]
We now allow up to 19 segments per wall (8 additional splits per floor / ceiling part). Allowing more than that, especially with the current codebase and workflow, would be completely overkill, so we won't be doing that.
