### ISSUE TITLE
Regarding official TR4

### ISSUE THREAD

**Issue by Luna-Blacklight** [MontyTRC89/Tomb-Editor#881]
Hello I have a question regarding the official Tomb Raider: The Last Revelation. Can I use the modern editor that spits out .wad2 formats to mod the game? I was using the legacy editor before and was able to port edited objects using Fexmerger.

**Comment by Nickelony** [comment]
Hi,
I'm afraid Fexmerger won't work with .wad2 files, as the .wad2 format is completely different from the original .wad format.
I'm sorry, but we are not planning to add any sort of support for modding the original games, since the point of the Tomb Editor suite is to create new levels, rather than modify existing ones.
Even if we wanted, we don't even have any logic in the code that would allow us to modify already compiled levels, so we would have to write a brand-new system for that, which would take too much time to make and only a handful of people would realistically use it.
